import fs from 'fs';
import path from 'path';

const envPath = path.join(process.cwd(), '.env');

const defaultEnvContent = `# Local Development Environment Variables
# Generated by scripts/setup-env.ts

# Database Connection
# Use a local PostgreSQL database or a Neon connection string
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/grant_tracking?sslmode=disable"

# Service Token (for internal API security)
# Can be any random string for local dev
SERVICE_BOT_TOKEN="local-dev-secret-token-123"

# GitHub Integration (Optional for local dev, required for risk scan)
GITHUB_TOKEN=""

# Discord Integration (Required by config.ts validation)
# You can use dummy values if you don't need Discord features locally,
# but the app will crash if these are missing.
DISCORD_BOT_TOKEN_COMMANDER="dummy_bot_token"
DISCORD_APP_ID_COMMANDER="123456789012345678"
DISCORD_GUILD_ID="123456789012345678"
DISCORD_PUBLIC_KEY="dummy_public_key"

# Backend URL
BACKEND_URL="http://localhost:3001"
`;

async function main() {
  console.log('🔍 Checking environment configuration...');

  if (fs.existsSync(envPath)) {
    console.log('✅ .env file already exists. Skipping generation.');
    console.log('👉 If you need to regenerate it, delete the existing .env file and run this script again.');
  } else {
    console.log('📝 Creating .env file with default local configuration...');
    fs.writeFileSync(envPath, defaultEnvContent.trim());
    console.log('✅ .env file created successfully!');
    console.log('⚠️  NOTE: "DATABASE_URL" is set to a local Postgres default. Please update it if your DB credentials differ.');
    console.log('⚠️  NOTE: Discord tokens are set to dummy values. Discord features will not work until you provide real credentials.');
  }
}

main();
